config/routes.rb
Rails.application.routes.draw do

  resources :sumas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/suma.rb
class Suma < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sumas_controller.rb
class SumasController < ApplicationController
  before_action :set_suma, only: [:show, :edit, :update, :destroy]

  # GET /sumas
  # GET /sumas.json
  def index
    @sumas = Suma.all
  end

  # GET /sumas/1
  # GET /sumas/1.json
  def show

    @suma = Suma.last
    @respuestasuma = Websuma.new(@suma.uno.to_s, @suma.dos.to_s)
    @suma.add_result = @respuestasuma.add_result
    @suma.save


  end

  # GET /sumas/new
  def new
    @suma = Suma.new
  end

  # GET /sumas/1/edit
  def edit
  end

  # POST /sumas
  # POST /sumas.json
  def create
    @suma = Suma.new(suma_params)

    respond_to do |format|
      if @suma.save
        format.html { redirect_to @suma, notice: 'Suma was successfully created.' }
        format.json { render :show, status: :created, location: @suma }
      else
        format.html { render :new }
        format.json { render json: @suma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sumas/1
  # PATCH/PUT /sumas/1.json
  def update
    respond_to do |format|
      if @suma.update(suma_params)
        format.html { redirect_to @suma, notice: 'Suma was successfully updated.' }
        format.json { render :show, status: :ok, location: @suma }
      else
        format.html { render :edit }
        format.json { render json: @suma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sumas/1
  # DELETE /sumas/1.json
  def destroy
    @suma.destroy
    respond_to do |format|
      format.html { redirect_to sumas_url, notice: 'Suma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suma
      @suma = Suma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suma_params
      params.require(:suma).permit(:uno, :dos, :add_result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/respuesta_helper.rb
module RespuestaHelper
end

app/helpers/sumas_helper.rb
module SumasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webserv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sumas/_form.html.erb
<%= form_with(model: suma, local: true) do |form| %>
  <% if suma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suma.errors.count, "error") %> prohibited this suma from being saved:</h2>

      <ul>
      <% suma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :uno %>
    <%= hidden_field_tag :a, params[:a] %>
  </div>
    +
  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :dos %>
    <%= hidden_field_tag :b, params[:b] %>
  </div>

  <div class="field">
    <%= form.hidden_field :add_result %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sumas/edit.html.erb
<h1>Editing Suma</h1>

<%= render 'form', suma: @suma %>

<%= link_to 'Show', @suma %> |
<%= link_to 'Back', sumas_path %>

app/views/sumas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sumas</h1>

<table>
  <thead>
    <tr>
      <th>Uno</th>
      <th>+</th>
      <th>Dos</th>
      <th>=</th>
      <th>Resultado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sumas.each do |suma| %>
      <tr>
        <td><%= suma.uno %></td>
        <td>+</td>
        <td><%= suma.dos %></td>
        <td>=</td>
        <td><%= suma.add_result %></td>
        <td><%= link_to 'Show', suma %></td>
        <td><%= link_to 'Edit', edit_suma_path(suma) %></td>
        <td><%= link_to 'Destroy', suma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Suma', new_suma_path %>

app/views/sumas/new.html.erb
<h1>New Suma</h1>

<%= render 'form', suma: @suma %>

<%= link_to 'Back', sumas_path %>

app/views/sumas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uno:</strong>
  <%= @suma.uno %>
</p>

<p>
  <strong>Dos:</strong>
  <%= @suma.dos %>
</p>

<p>
  <strong>Res:</strong>
  <%= @suma.add_result %>
</p>

<%= link_to 'Edit', edit_suma_path(@suma) %> |
<%= link_to 'Back', sumas_path %>